version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "443:443" # HTTPS для Telegram Mini Apps
    depends_on:
      - server
    volumes:
      - ./ssl:/etc/nginx/ssl # Папка с сертификатами для HTTPS

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydatabase
    volumes:
      - ./server/uploads:/app/uploads # Для хранения файлов
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: